// Central product catalogue. Specs drawn from Arpha / FUWEI product materials.
// deviceType maps to a CSS visual: 'lock' | 'bell' | 'cam' | 'dash' | 'brush' | 'beauty' | 'plug' | 'bulb'
// availableIn: if set, product only appears for those locale codes.
//   Products WITHOUT availableIn are shown for all non-regional locales.
//   Canadian products: availableIn: ['en-ca', 'fr-ca']
//   Japan products:    availableIn: ['ja', 'en-jp']

const CANADIAN_LOCALES = ["en-ca", "fr-ca"];
const JAPAN_LOCALES = ["ja", "en-jp"];
const REGIONAL_LOCALES = [...CANADIAN_LOCALES, ...JAPAN_LOCALES];

export const CATEGORIES = [
  { key: "Smart Lock", label: "Smart Locks", blurb: "Deadbolt, push-pull and retrofit locks with biometric entry." },
  { key: "Doorbell", label: "Video Doorbells", blurb: "See, hear and speak to whoever's at the door." },
  { key: "IP Camera", label: "IP Cameras", blurb: "Indoor and outdoor cameras with live two-way audio." },
  { key: "Dash Cam", label: "Dash Cams", blurb: "Smart-driving recorders for the road." },
];

export const CA_CATEGORIES = [
  { key: "Personal Care", label: "Personal Care", blurb: "Smart devices for everyday health and beauty." },
  { key: "Home Appliance", label: "Home Appliances", blurb: "Connected plugs, lighting and cameras for the smart home." },
];

export const JP_CATEGORIES = [
  { key: "Smart Lock", label: "Smart Locks", blurb: "Fingerprint, camera and voice control — security reimagined." },
];

export const PRODUCTS = [
  // ── Global products (all non-Canadian locales) ─────────────────────────────
  {
    slug: "uvo-2",
    name: "DF360",
    model: "",
    category: "Smart Lock",
    sub: "Deadbolt",
    deviceType: "lock",
    image: "/products/DF360 Display.jpg",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: "Flagship",
    badgeAlt: true,
    price: 279,
    was: 399,
    tagline: "Premium access with facial and palm vein recognition.",
    description:
      "The ultimate door lock that combines both face and palm that makes entry so easy. Choose how to enter with the premium finish that you come to love.",
    feature: ["Face", "Palm Vein", "App", "Compact"],
    unlock: ["Face", "Palm", "Keypad", "Phone", "Key"],
    highlights: [
      { icon: "Face", title: "Face Recognition", body: "Quick, reliable biometric entry for the whole household." },
      { icon: "Palm", title: "Palm Vein Recognition", body: "Use the force to open the door. Wave and have it magically unlock your door." },
      { icon: "ShieldCheck", title: "All-metal body", body: "A compact, durable build that looks at home on any door." },
      { icon: "Phone", title: "App control", body: "Remote unlock, set codes and much more." },
    ],
    specs: [
      { k: "Recognition", v: "Facial / Palm Vein" },
      { k: "Unlock speed", v: "<0.3s" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE" },
      { k: "Weather rating", v: "IP54" },
      { k: "Material", v: "All-metal" },
      { k: "Power", v: "Rechargeable lithium" },
      { k: "Install", v: "Standard deadbolt" },
      { k: "Backup", v: "Mechanical key" },
    ],
  },
  {
    slug: "primo-l800",
    name: "Primo",
    model: "",
    category: "Smart Lock",
    sub: "Deadbolt",
    deviceType: "lock",
    image: "/products/primo.png",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: "Upcoming",
    price: 279,
    was: 299,
    tagline: "Your hand is the key.",
    description:
      "Primo brings a clean touchscreen keypad and palm vein reader to a slim deadbolt body — a quiet, modern upgrade for the everyday front door.",
    feature: ["Palm Vein", "Touchscreen", "Card", "App"],
    unlock: ["Palm", "Keypad", "Card", "Phone", "Key"],
    highlights: [
      { icon: "Keypad", title: "Touchscreen keypad", body: "Anti-peek code entry on a responsive glass surface." },
      { icon: "Palm", title: "Palm Vein Unlock", body: "Fast biometric access without reaching for keys." },
      { icon: "Phone", title: "Remote access", body: "Lock, unlock and grant access from the Arpha app." },
    ],
    specs: [
      { k: "Recognition", v: "Palm Vein" },
      { k: "Keypad", v: "Touchscreen" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE" },
      { k: "Weather rating", v: "IP54" },
      { k: "Power", v: "Rechargeable lithium" },
      { k: "Install", v: "Standard deadbolt" },
      { k: "Backup", v: "Mechanical key" },
    ],
  },
  {
    slug: "core-sf302",
    name: "Core",
    model: "",
    category: "Smart Lock",
    sub: "Deadbolt",
    deviceType: "lock",
    image: "/products/core.png",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: "Best seller",
    price: 179,
    was: 199,
    tagline: "Every family member can register 5 fingerprints each.",
    description:
      "Core is the easiest way into a smart home — a fingerprint deadbolt that replaces your existing one with four screws and no wiring. Sub-0.3s fingerprint unlock, app control, and Alexa and Google Home built right in.",
    feature: ["Fingerprint", "Wi-Fi", "DIY", "Voice"],
    unlock: ["Fingerprint", "Keypad", "Voice", "Phone"],
    highlights: [
      { icon: "Fingerprint", title: "Fast fingerprint", body: ">99% accuracy, unlocking in under 0.3 seconds." },
      { icon: "Doc", title: "15-minute DIY", body: "Replaces a standard deadbolt with four screws — no drilling, no locksmith." },
      { icon: "Voice", title: "Voice ready", body: "Ask Alexa or Google Home to check or lock your door." },
    ],
    specs: [
      { k: "Recognition", v: "Fingerprint" },
      { k: "Accuracy", v: ">99%" },
      { k: "Unlock speed", v: "<0.3s" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE 5.1" },
      { k: "Voice", v: "Alexa, Google Home" },
      { k: "Weather rating", v: "IP54" },
      { k: "Material", v: "Aluminium alloy" },
      { k: "Power", v: "8 x AA batteries" },
      { k: "Install", v: "15-min DIY deadbolt" },
      { k: "Lock body", v: "Motorised" },
    ],
  },
  {
    slug: "holt-lite-h10",
    name: "Holt Lite",
    model: "H10",
    category: "Smart Lock",
    sub: "Big Lock",
    deviceType: "lock",
    image: "/products/h10.jpg",
    badge: "Upcoming",
    badgeAlt: false,
    price: 399,
    was: 459,
    tagline: "3D face and palm-vein recognition in a fully silent push-pull lock.",
    description:
      "The Holt Lite is Arpha's flagship door lock — dual cameras, a 4.5-inch HD indoor display and an unlock you barely have to think about. Walk up, it recognises your face or palm vein in under half a second, and the motorised body opens without a sound.",
    feature: ["3D Face", "Palm Vein", "2K Camera", "Multi-point"],
    unlock: ["Face", "Palm", "Fingerprint", "Keypad", "Card", "Phone", "Key"],
    highlights: [
      { icon: "Face", title: "3D Face & Palm Vein", body: ">99% accuracy and under 0.5s to recognise you — in daylight or pitch dark." },
      { icon: "Camera", title: "Dual cameras", body: "2K outdoor and 480P indoor cameras with motion detection and live two-way talk." },
      { icon: "Battery", title: "Solid-state power", body: "5000 mAh solid-state plus a 2250 mAh lithium-ion backup keep it running for months." },
    ],
    specs: [
      { k: "Recognition", v: "3D Face + Palm Vein" },
      { k: "Accuracy", v: ">99%" },
      { k: "Unlock speed", v: "<0.5s" },
      { k: "Outdoor camera", v: "2K" },
      { k: "Indoor camera", v: "480P" },
      { k: "Display", v: "4.5\" HD" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE 5.4" },
      { k: "Lock body", v: "Motorised, multi-point" },
      { k: "Weather rating", v: "IP52" },
      { k: "Battery", v: "5000 + 2250 mAh" },
      { k: "Material", v: "Premium metal" },
      { k: "Backup", v: "Mechanical key" },
    ],
  },
  {
    slug: "duo",
    name: "Doorbell Duo",
    model: "",
    category: "Doorbell",
    sub: "Video Doorbell",
    deviceType: "bell",
    image: "/products/Doorbell Duo.jpg",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: null,
    price: 159,
    was: 179.99,
    tagline: "All-in-one Battery and Wired together as one unit.",
    description:
      "Duo is a fuss-free wireless doorbell — slim, weatherproof and easy to mount, with an included chime and PIR sensing so you never miss a visitor.",
    feature: ["Wireless", "Chime", "PIR", "Remote"],
    unlock: ["Phone"],
    highlights: [
      { icon: "Bell", title: "Plug-in chime", body: "A wireless chime you can place anywhere in the home." },
      { icon: "Camera", title: "Clear view", body: "Wide-angle camera with night vision for round-the-clock cover." },
      { icon: "Phone", title: "Remote access", body: "Answer and watch from the Arpha app wherever you are." },
    ],
    specs: [
      { k: "Resolution", v: "1080P" },
      { k: "Field of view", v: "162°" },
      { k: "Detection", v: "PIR motion" },
      { k: "Chime", v: "Included" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz" },
      { k: "Power", v: "Rechargeable battery" },
      { k: "Weather rating", v: "IP54" },
    ],
  },
  {
    slug: "battery-k25",
    name: "K25",
    model: "",
    category: "IP Camera",
    sub: "Battery",
    deviceType: "cam",
    image: "/products/k25.png",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: null,
    price: 119,
    was: 149,
    tagline: "Pan-tilt battery camera with motion tracking.",
    description:
      "The K25 watches the room and follows the action. A pan-tilt head with motion tracking, colour night vision and live two-way audio — all running on battery, so it goes wherever you need cover.",
    feature: ["Pan/Tilt", "Battery", "Tracking", "Two-Way"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "Pan & tilt", body: "A motorised head that scans the room and tracks movement." },
      { icon: "Battery", title: "Wire-free", body: "Rechargeable battery means no outlet, no cabling, anywhere." },
      { icon: "Voice", title: "Two-way audio", body: "Hear and speak to the room from the Arpha app." },
    ],
    specs: [
      { k: "Resolution", v: "2K" },
      { k: "Movement", v: "Pan / tilt + tracking" },
      { k: "Night vision", v: "Colour" },
      { k: "Audio", v: "Two-way" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz" },
      { k: "Power", v: "Rechargeable battery" },
      { k: "Storage", v: "Cloud / microSD" },
    ],
  },
  {
    slug: "poe-k15",
    name: "K15",
    model: "",
    category: "IP Camera",
    sub: "PoE",
    deviceType: "cam",
    badge: null,
    price: 129,
    was: 149,
    tagline: "Always-on PoE camera for continuous recording.",
    description:
      "The K15 runs on Power-over-Ethernet for a single-cable install and uninterrupted recording — ideal for entrances, driveways and anywhere you want eyes around the clock.",
    feature: ["PoE", "24/7", "Pan/Tilt", "Tracking"],
    unlock: [],
    highlights: [
      { icon: "Plug", title: "Single-cable PoE", body: "Power and data over one Ethernet cable for reliable, always-on cover." },
      { icon: "Camera", title: "Pan & tilt", body: "Motorised tracking keeps moving subjects in frame." },
      { icon: "ShieldCheck", title: "Continuous record", body: "24/7 recording with no battery to swap or recharge." },
    ],
    specs: [
      { k: "Resolution", v: "2K" },
      { k: "Movement", v: "Pan / tilt + tracking" },
      { k: "Night vision", v: "Colour" },
      { k: "Audio", v: "Two-way" },
      { k: "Connectivity", v: "PoE Ethernet" },
      { k: "Recording", v: "24/7" },
      { k: "Storage", v: "NVR / cloud" },
    ],
  },
  {
    slug: "m660",
    name: "M660",
    model: "M660",
    category: "Dash Cam",
    sub: "Smart Driving",
    deviceType: "dash",
    image: "/products/M660.png",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: "3-channel",
    price: 249,
    was: 299,
    tagline: "Three-channel driving recorder with night clarity.",
    description:
      "The M660 records the road ahead, the cabin and the rear at once. Wide field of view, strong night vision and the same Arpha reliability you trust at the front door — now for the drive.",
    feature: ["3 Camera", "Night Vision", "Wide FOV", "Loop"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "Three channels", body: "Front, cabin and rear captured together in one device." },
      { icon: "Weather", title: "Night vision", body: "Clear footage after dark and in low light." },
      { icon: "Bolt", title: "Smart capture", body: "Loop recording with impact-triggered event saving." },
    ],
    specs: [
      { k: "Channels", v: "3 (front / cabin / rear)" },
      { k: "Resolution", v: "Up to 2K" },
      { k: "Field of view", v: "Wide-angle" },
      { k: "Night vision", v: "Yes" },
      { k: "Recording", v: "Loop + event" },
      { k: "Storage", v: "microSD" },
    ],
  },
  {
    slug: "m350",
    name: "M350",
    model: "M350",
    category: "Dash Cam",
    sub: "Smart Driving",
    deviceType: "dash",
    image: "/products/m350 v2.png",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: null,
    price: 119,
    was: 199,
    tagline: "Dual-channel dash cam with front and cabin view.",
    description:
      "A compact dual-channel recorder that keeps an eye on the road and the cabin — straightforward, dependable footage for everyday driving and ride-share peace of mind.",
    feature: ["2 Camera", "Night Vision", "Loop", "Compact"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "Front & cabin", body: "Two channels covering the road ahead and inside the car." },
      { icon: "Weather", title: "Low-light ready", body: "Night vision keeps plates and faces legible after dark." },
      { icon: "Bolt", title: "Loop & event", body: "Continuous loop recording with automatic incident saving." },
    ],
    specs: [
      { k: "Channels", v: "2 (front / cabin)" },
      { k: "Resolution", v: "1080P" },
      { k: "Night vision", v: "Yes" },
      { k: "Recording", v: "Loop + event" },
      { k: "Storage", v: "microSD" },
      { k: "Mount", v: "Adhesive" },
    ],
  },

  // ── Canadian-market products (en-ca, fr-ca only) ──────────────────────────
  {
    slug: "x3-toothbrush",
    name: "X3",
    model: "X3",
    category: "Personal Care",
    sub: "Electric Toothbrush",
    deviceType: "brush",
    image: "/products/x3.jpg",
    imageLight: true,
    imageFill: true,
    badge: "Kids",
    availableIn: ["en-ca", "fr-ca"],
    price: 29,
    tagline: "Smart brushing for happy kids — twice daily made fun.",
    description:
      "The X3 Kids Smart Electric Toothbrush addresses the real challenges of children's oral health with a warm, positive experience that builds lasting healthy habits.",
    feature: ["Kids", "Smart Timer", "Soft Bristles", "App"],
    unlock: [],
    highlights: [
      { icon: "ShieldCheck", title: "Designed for kids", body: "Soft bristles and a gentle mode make brushing comfortable for all ages." },
      { icon: "Bolt", title: "Built-in timer", body: "Encourages the recommended 2-minute brushing routine every time." },
      { icon: "Phone", title: "Arpha app", body: "Track brushing habits and reward good hygiene via the companion app." },
    ],
    specs: [
      { k: "Suitable age", v: "3+" },
      { k: "Mode", v: "Gentle kids mode" },
      { k: "Timer", v: "2-minute built-in" },
      { k: "Bristles", v: "Soft antibacterial" },
      { k: "Connectivity", v: "Bluetooth" },
      { k: "Power", v: "USB rechargeable" },
    ],
  },
  {
    slug: "gf7-toothbrush",
    name: "GF-7",
    model: "GF-7",
    category: "Personal Care",
    sub: "Electric Toothbrush",
    deviceType: "brush",
    image: "/products/toothbrush.jpg",
    imageFill: true,
    badge: "Best Seller",
    availableIn: ["en-ca", "fr-ca"],
    price: 49,
    was: 69,
    tagline: "A wonderful day starts with it.",
    description:
      "The GF-7 combines ultrasonic vibration with antibacterial bristles across three smart modes — Cleaning, Whitening and Gum Care — for a complete oral health routine in two minutes.",
    feature: ["Ultrasonic", "3 Modes", "Antibacterial", "USB"],
    unlock: [],
    highlights: [
      { icon: "Bolt", title: "30,000 vibrations/min", body: "Ultrasonic motor removes plaque and whitens with every stroke." },
      { icon: "ShieldCheck", title: "Antibacterial bristles", body: "Prevents bacterial growth between uses and eliminates bad breath." },
      { icon: "Battery", title: "7-day battery", body: "Full charge lasts a week — USB rechargeable in just 3 hours." },
    ],
    specs: [
      { k: "Vibration frequency", v: "30,000 times/min" },
      { k: "Modes", v: "Cleaning / Whitening / Gum Care" },
      { k: "Battery", v: "320 mAh" },
      { k: "Charging time", v: "3 hours" },
      { k: "Working time", v: "7 days" },
      { k: "Rated power", v: "1W" },
      { k: "Interface", v: "USB" },
      { k: "Dimensions", v: "239 × 21 mm" },
    ],
  },
  {
    slug: "x1-beauty",
    name: "X1",
    model: "X1",
    category: "Personal Care",
    sub: "Beauty Instrument",
    deviceType: "beauty",
    image: "/products/beauty.jpg",
    imageFill: true,
    badge: null,
    availableIn: ["en-ca", "fr-ca"],
    price: 59,
    was: 79,
    tagline: "Enjoy deep purity for your skin.",
    description:
      "The X1 facial cleansing device uses adjustable ultrasonic vibration in two motion types — vertical and rotating — to remove oil, makeup residue, dirt and blackheads with a premium aviation-grade aluminium build.",
    feature: ["Ultrasonic", "3-Gear", "Aluminium", "Waterproof"],
    unlock: [],
    highlights: [
      { icon: "Bolt", title: "3-gear ultrasonic vibration", body: "Adjustable intensity with vertical and rotating modes for different skin needs." },
      { icon: "ShieldCheck", title: "Aviation-grade aluminium", body: "Premium build that's anti-fading, waterproof and made to last." },
      { icon: "Battery", title: "1-hour working time", body: "700 mAh battery lasts through your full skincare routine." },
    ],
    specs: [
      { k: "Vibration modes", v: "3-gear (vertical + rotating)" },
      { k: "Material", v: "Aviation-grade aluminium" },
      { k: "Battery", v: "700 mAh" },
      { k: "Charging time", v: "8 hours" },
      { k: "Working time", v: "1 hour" },
      { k: "Rated power", v: "3W" },
      { k: "Interface", v: "USB" },
      { k: "Waterproof", v: "Yes" },
      { k: "Dimensions", v: "144 × 40 × 36 mm" },
    ],
  },
  {
    slug: "p1-smart-plug",
    name: "P1",
    model: "P1",
    category: "Home Appliance",
    sub: "Smart Plug",
    deviceType: "plug",
    image: "/products/smartsocket.jpg",
    imageLight: true,
    imageFill: true,
    badge: null,
    availableIn: ["en-ca", "fr-ca"],
    price: 19,
    tagline: "Turn any outlet into a smart outlet.",
    description:
      "The P1 Wi-Fi Smart Socket connects to your home network for remote control of any connected device. Set schedules, monitor usage and control from anywhere via the Arpha app.",
    feature: ["Wi-Fi", "15A", "Schedules", "App"],
    unlock: [],
    highlights: [
      { icon: "Plug", title: "Wi-Fi connected", body: "Control any plugged-in device remotely via the Arpha app." },
      { icon: "Phone", title: "Schedules & timers", body: "Automate your home with custom schedules and countdowns." },
      { icon: "ShieldCheck", title: "15A capacity", body: "Handles high-draw appliances safely with ABS+PC construction." },
    ],
    specs: [
      { k: "Connectivity", v: "Wi-Fi 2.4GHz (802.11 b/g/n)" },
      { k: "Rated current", v: "15A" },
      { k: "Rated voltage", v: "AC 125V, 50/60Hz" },
      { k: "Material", v: "ABS+PC" },
      { k: "Operating temp", v: "-10°C to 45°C" },
      { k: "Security", v: "WPA2-PSK (AES)" },
      { k: "Dimensions", v: "70 × 40 × 50 mm" },
      { k: "Colour", v: "White" },
    ],
  },
  {
    slug: "p4-power-strip",
    name: "P4",
    model: "P4",
    category: "Home Appliance",
    sub: "Smart Power Strip",
    deviceType: "plug",
    image: "/products/extention.jpg",
    imageFill: true,
    badge: "Voice Ready",
    availableIn: ["en-ca", "fr-ca"],
    price: 49,
    was: 59,
    tagline: "Power your smart home, all at once.",
    description:
      "The P4 Smart Power Strip brings Wi-Fi control to multiple outlets at once. Schedule, command and automate your devices with voice control via Alexa and Google Assistant.",
    feature: ["Wi-Fi", "Voice", "Schedules", "Multi-outlet"],
    unlock: [],
    highlights: [
      { icon: "Voice", title: "Alexa & Google", body: "Voice control your connected devices hands-free." },
      { icon: "Phone", title: "App control", body: "Control individual outlets and set custom schedules remotely." },
      { icon: "Plug", title: "Multi-outlet", body: "Power multiple devices with smart control over each one." },
    ],
    specs: [
      { k: "Connectivity", v: "Wi-Fi 2.4GHz (802.11 b/g/n)" },
      { k: "Rated current", v: "10A" },
      { k: "Rated voltage", v: "AC 100–240V" },
      { k: "Voice", v: "Alexa, Google Assistant" },
      { k: "Material", v: "ABS+PC" },
      { k: "Operating temp", v: "-10°C to 45°C" },
      { k: "Security", v: "WPA2-PSK" },
      { k: "Dimensions", v: "260 × 60 × 26 mm" },
      { k: "Colour", v: "White" },
    ],
  },
  {
    slug: "lc-led-bulb",
    name: "LC",
    model: "LC",
    category: "Home Appliance",
    sub: "Smart Lighting",
    deviceType: "bulb",
    image: "/products/lightbulb.jpg",
    imageFill: true,
    badge: null,
    availableIn: ["en-ca", "fr-ca"],
    price: 24,
    tagline: "Any mood. Any colour. Any room.",
    description:
      "The LC Smart LED Bulb gives you full-spectrum RGB and tunable white light from 2700K warm to 6500K daylight — all controlled from the Arpha app or by voice, anywhere in the world.",
    feature: ["RGB+CCT", "Wi-Fi", "Voice", "20,000hr"],
    unlock: [],
    highlights: [
      { icon: "Phone", title: "Full-colour app control", body: "16 million colours and tunable white from warm to daylight." },
      { icon: "Voice", title: "Voice & scenes", body: "Group bulbs into scenes and control with Alexa or Google Assistant." },
      { icon: "ShieldCheck", title: "20,000-hour lifespan", body: "Long-lasting 9W LED with 800 lm output for any space." },
    ],
    specs: [
      { k: "Connectivity", v: "Wi-Fi 2.4GHz (802.11 b/g/n)" },
      { k: "Base", v: "E26" },
      { k: "Power", v: "9W" },
      { k: "Luminous flux", v: "800 lm" },
      { k: "Colour range", v: "RGB + 2700K–6500K white" },
      { k: "Lifespan", v: "20,000 hours" },
      { k: "Rated voltage", v: "AC 100–240V" },
      { k: "Security", v: "WPA2-PSK (AES)" },
      { k: "Dimensions", v: "60 × 60 × 115 mm" },
    ],
  },
  {
    slug: "wifi-cam-ip65",
    name: "WiFi Cam",
    model: "IP65",
    category: "Home Appliance",
    sub: "Smart Camera",
    deviceType: "cam",
    image: "/products/smartcam.jpg",
    imageFill: true,
    badge: "IP65",
    availableIn: ["en-ca", "fr-ca"],
    price: 69,
    was: 89,
    tagline: "Pan, tilt and watch — rain or shine.",
    description:
      "The WiFi Cam IP65 is an outdoor-ready security camera with 355° horizontal and 90° vertical rotation, HD live streaming, night vision up to 65 ft and two-way audio — all accessible from the Arpha app.",
    feature: ["1080P", "Pan/Tilt", "IP65", "Two-Way"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "355° × 90° pan-tilt", body: "Full-room coverage with motorised horizontal and vertical sweep." },
      { icon: "ShieldCheck", title: "IP65 weatherproof", body: "Built for outdoor use — dust-proof and rain-resistant." },
      { icon: "Voice", title: "Two-way audio", body: "Mic and speaker built in for real-time conversation." },
    ],
    specs: [
      { k: "Resolution", v: "1080P" },
      { k: "Rotation", v: "Horizontal 355° / Vertical 90°" },
      { k: "Night vision", v: "65 ft (20 m)" },
      { k: "Audio", v: "Two-way (mic + speaker)" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz" },
      { k: "Weather rating", v: "IP65" },
      { k: "Lens", v: "3.6mm" },
      { k: "Power", v: "DC 5V 1.5A" },
      { k: "Dimensions", v: "65 × 65 × 119 mm" },
    ],
  },
  {
    slug: "dx95-cam",
    name: "DX95",
    model: "DX95",
    category: "Home Appliance",
    sub: "Smart Camera",
    deviceType: "cam",
    image: "/products/aitracking.jpg",
    imageLight: true,
    imageFill: true,
    badge: "AI Tracking",
    badgeAlt: true,
    availableIn: ["en-ca", "fr-ca"],
    price: 89,
    was: 109,
    tagline: "AI tracking security — no subscription needed.",
    description:
      "The DX95 is a compact indoor security camera with AI-powered motion tracking, local microSD storage up to 128 GB and a magnetic base for flexible mounting — complete privacy with no cloud fees.",
    feature: ["AI Tracking", "Local Storage", "Magnetic", "Night Vision"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "AI motion tracking", body: "Automatically follows subjects within 180° so you never miss the action." },
      { icon: "ShieldCheck", title: "No cloud subscription", body: "All footage stored locally on microSD — up to 128 GB, zero monthly fees." },
      { icon: "Battery", title: "Magnetic mount", body: "Compact 108 g body with a magnetic base — attach anywhere in seconds." },
    ],
    specs: [
      { k: "Resolution", v: "2592 × 1944" },
      { k: "AI tracking", v: "180° rotation" },
      { k: "Night vision", v: "32 ft (10 m)" },
      { k: "Storage", v: "microSD up to 128 GB" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz" },
      { k: "Power", v: "5W" },
      { k: "Weight", v: "108 g" },
      { k: "Lens", v: "2.2mm, 1/2.7\"" },
      { k: "Microphone range", v: "16 ft (5 m)" },
      { k: "Dimensions", v: "62 × 36 × 110 mm" },
    ],
  },

  // ── Japan-market products (ja, en-jp only) ────────────────────────────────
  {
    slug: "aku",
    name: "Aku",
    model: "",
    category: "Smart Lock",
    sub: "Smart Lock with Camera",
    deviceType: "lock",
    image: "/products/akudoor.png",
    imageStyle: { objectFit: "cover", padding: "0", position: "absolute", inset: "0", width: "100%", height: "100%" },
    badge: "2K Camera",
    badgeAlt: true,
    availableIn: ["ja", "en-jp"],
    price: 249,
    tagline: "Smart lock with built-in 2K camera and AI detection.",
    description:
      "The Aku combines fingerprint access, voice control and a built-in 2K wide-angle camera into one elegant smart lock. With 5,200 mAh dual batteries, AI motion detection and two-way talk, your door does more than just lock.",
    feature: ["2K Camera", "Fingerprint", "IP65", "5200mAh"],
    unlock: ["Fingerprint", "Keypad", "Voice", "Phone", "Key"],
    highlights: [
      { icon: "Camera", title: "Built-in 2K camera", body: "160° wide-angle lens with AI motion detection, night vision and two-way talk built right in." },
      { icon: "Fingerprint", title: "Multi-method access", body: "Fingerprint, PIN, app, voice and mechanical key — enter however you prefer." },
      { icon: "Battery", title: "6-month battery life", body: "5,200 + 2,600 mAh dual removable batteries with USB-C emergency backup." },
      { icon: "ShieldCheck", title: "IP65 weatherproof", body: "Anti-peep codes, duress mode, door-left-open alerts and auto-lock keep your home safe." },
    ],
    specs: [
      { k: "Camera", v: "2K (2048×1536), 160° wide-angle" },
      { k: "Night vision", v: "850nm IR, auto IR-cut" },
      { k: "Recognition", v: "Fingerprint" },
      { k: "Unlock methods", v: "Fingerprint / PIN / App / Voice / Key" },
      { k: "Voice", v: "Alexa, Google Home" },
      { k: "Weather rating", v: "IP65" },
      { k: "Battery", v: "5,200 + 2,600 mAh (removable)" },
      { k: "Battery life", v: "~6 months" },
      { k: "Emergency power", v: "USB-C" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, Bluetooth" },
      { k: "Auto-lock", v: "0–900 sec configurable" },
      { k: "AI detection", v: "Human, all-motion, zone" },
      { k: "Chime", v: "433 MHz wireless indoor chime" },
      { k: "Operating temp", v: "-20°C to 55°C" },
      { k: "App", v: "Arpha Plus (iOS 13+ / Android 5.0+)" },
      { k: "Certifications", v: "UN38.3 · MSDS · PSE" },
    ],
  },
];

export function getProduct(slug) {
  return PRODUCTS.find((p) => p.slug === slug);
}

// Returns products visible for a given locale.
// Products with no availableIn show for all non-regional locales.
// Products with availableIn only show in those specific locales.
export function getProductsForLocale(lang) {
  const isRegional = REGIONAL_LOCALES.includes(lang);
  return PRODUCTS.filter((p) => {
    if (p.availableIn) return p.availableIn.includes(lang);
    return !isRegional;
  });
}

export function getCategoriesForLocale(lang) {
  if (CANADIAN_LOCALES.includes(lang)) return CA_CATEGORIES;
  if (JAPAN_LOCALES.includes(lang)) return JP_CATEGORIES;
  return CATEGORIES;
}

export function getByCategory(key, lang) {
  const pool = lang ? getProductsForLocale(lang) : PRODUCTS;
  return pool.filter((p) => p.category === key);
}

export function getRelated(slug, n = 3, lang) {
  const cur = getProduct(slug);
  if (!cur) return [];
  const pool = lang ? getProductsForLocale(lang) : PRODUCTS;
  const same = pool.filter((p) => p.category === cur.category && p.slug !== slug);
  const rest = pool.filter((p) => p.category !== cur.category);
  return [...same, ...rest].slice(0, n);
}
