// Central product catalogue. Specs drawn from Arpha / FUWEI product materials.
// deviceType maps to a CSS visual: 'lock' | 'bell' | 'cam' | 'dash'

export const CATEGORIES = [
  { key: "Smart Lock", label: "Smart Locks", blurb: "Deadbolt, push-pull and retrofit locks with biometric entry." },
  { key: "Doorbell", label: "Video Doorbells", blurb: "See, hear and speak to whoever's at the door." },
  { key: "IP Camera", label: "IP Cameras", blurb: "Indoor and outdoor cameras with live two-way audio." },
  { key: "Dash Cam", label: "Dash Cams", blurb: "Smart-driving recorders for the road." },
];

export const PRODUCTS = [
  {
    slug: "uvo-2",
    name: "DF360",
    model: "",
    category: "Smart Lock",
    sub: "Deadbolt",
    deviceType: "lock",
    image: "/products/DF360 Display.jpg",
    imageStyle: { objectFit: "cover", padding: "0" },
    badge: "Flagship",
    badgeAlt: true,
    price: 279,
    was: 399,
    tagline: "Compact all-metal deadbolt, refined for any standard door.",
    description:
      "The second-generation Uvo keeps everything people loved and trims the rest — a smaller, all-metal body with fingerprint, card and app entry that fits cleanly on any standard door.",
    feature: ["Fingerprint", "Card", "App", "Compact"],
    unlock: ["Fingerprint", "Keypad", "Card", "Phone", "Key"],
    highlights: [
      { icon: "Fingerprint", title: "Fingerprint first", body: "Quick, reliable biometric entry for the whole household." },
      { icon: "ShieldCheck", title: "All-metal body", body: "A compact, durable build that looks at home on any door." },
      { icon: "Phone", title: "App control", body: "Share access, set codes and check history from anywhere." },
    ],
    specs: [
      { k: "Recognition", v: "Fingerprint" },
      { k: "Unlock speed", v: "<0.3s" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE" },
      { k: "Weather rating", v: "IP54" },
      { k: "Material", v: "All-metal" },
      { k: "Power", v: "Rechargeable lithium" },
      { k: "Install", v: "Standard deadbolt" },
      { k: "Backup", v: "Mechanical key" },
    ],
  },
  {
    slug: "primo-l800",
    name: "Primo",
    model: "",
    category: "Smart Lock",
    sub: "Deadbolt",
    deviceType: "lock",
    image: "/products/L600.png",
    imageStyle: { padding: "18% 26%" },
    badge: "Upcoming",
    price: 279,
    was: 299,
    tagline: "Slim touchscreen deadbolt with fingerprint and card entry.",
    description:
      "Primo brings a clean touchscreen keypad and fingerprint reader to a slim deadbolt body — a quiet, modern upgrade for the everyday front door.",
    feature: ["Fingerprint", "Touchscreen", "Card", "App"],
    unlock: ["Fingerprint", "Keypad", "Card", "Phone", "Key"],
    highlights: [
      { icon: "Keypad", title: "Touchscreen keypad", body: "Anti-peek code entry on a responsive glass surface." },
      { icon: "Fingerprint", title: "Fingerprint unlock", body: "Fast biometric access without reaching for keys." },
      { icon: "Phone", title: "Remote access", body: "Lock, unlock and grant access from the Arpha app." },
    ],
    specs: [
      { k: "Recognition", v: "Fingerprint" },
      { k: "Keypad", v: "Touchscreen" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE" },
      { k: "Weather rating", v: "IP54" },
      { k: "Power", v: "Rechargeable lithium" },
      { k: "Install", v: "Standard deadbolt" },
      { k: "Backup", v: "Mechanical key" },
    ],
  },
  {
    slug: "core-sf302",
    name: "Core",
    model: "",
    category: "Smart Lock",
    sub: "Deadbolt",
    deviceType: "lock",
    image: "/products/SF302.png",
    imageStyle: { padding: "18% 30%" },
    badge: "Best seller",
    price: 179,
    was: 199,
    tagline: "Fingerprint deadbolt you can fit yourself in 15 minutes.",
    description:
      "Core is the easiest way into a smart home — a fingerprint deadbolt that replaces your existing one with four screws and no wiring. Sub-0.3s fingerprint unlock, app control, and Alexa and Google Home built right in.",
    feature: ["Fingerprint", "Wi-Fi", "DIY", "Voice"],
    unlock: ["Fingerprint", "Keypad", "Voice", "Phone"],
    highlights: [
      { icon: "Fingerprint", title: "Fast fingerprint", body: ">99% accuracy, unlocking in under 0.3 seconds." },
      { icon: "Doc", title: "15-minute DIY", body: "Replaces a standard deadbolt with four screws — no drilling, no locksmith." },
      { icon: "Voice", title: "Voice ready", body: "Ask Alexa or Google Home to check or lock your door." },
    ],
    specs: [
      { k: "Recognition", v: "Fingerprint" },
      { k: "Accuracy", v: ">99%" },
      { k: "Unlock speed", v: "<0.3s" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE 5.1" },
      { k: "Voice", v: "Alexa, Google Home" },
      { k: "Weather rating", v: "IP54" },
      { k: "Material", v: "Aluminium alloy" },
      { k: "Power", v: "8 x AA batteries" },
      { k: "Install", v: "15-min DIY deadbolt" },
      { k: "Lock body", v: "Motorised" },
    ],
  },
  {
    slug: "holt-lite-h10",
    name: "Holt Lite",
    model: "H10",
    category: "Smart Lock",
    sub: "Big Lock",
    deviceType: "lock",
    image: "/products/h10.jpg",
    badge: "Upcoming",
    badgeAlt: false,
    price: 399,
    was: 459,
    tagline: "3D face and palm-vein recognition in a fully silent push-pull lock.",
    description:
      "The Holt Lite is Arpha's flagship door lock — dual cameras, a 4.5-inch HD indoor display and an unlock you barely have to think about. Walk up, it recognises your face or palm vein in under half a second, and the motorised body opens without a sound.",
    feature: ["3D Face", "Palm Vein", "2K Camera", "Multi-point"],
    unlock: ["Face", "Palm", "Fingerprint", "Keypad", "Card", "Phone", "Key"],
    highlights: [
      { icon: "Face", title: "3D Face & Palm Vein", body: ">99% accuracy and under 0.5s to recognise you — in daylight or pitch dark." },
      { icon: "Camera", title: "Dual cameras", body: "2K outdoor and 480P indoor cameras with motion detection and live two-way talk." },
      { icon: "Battery", title: "Solid-state power", body: "5000 mAh solid-state plus a 2250 mAh lithium-ion backup keep it running for months." },
    ],
    specs: [
      { k: "Recognition", v: "3D Face + Palm Vein" },
      { k: "Accuracy", v: ">99%" },
      { k: "Unlock speed", v: "<0.5s" },
      { k: "Outdoor camera", v: "2K" },
      { k: "Indoor camera", v: "480P" },
      { k: "Display", v: "4.5\" HD" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz, BLE 5.4" },
      { k: "Lock body", v: "Motorised, multi-point" },
      { k: "Weather rating", v: "IP52" },
      { k: "Battery", v: "5000 + 2250 mAh" },
      { k: "Material", v: "Premium metal" },
      { k: "Backup", v: "Mechanical key" },
    ],
  },
  {
    slug: "duo",
    name: "Doorbell Duo",
    model: "",
    category: "Doorbell",
    sub: "Video Doorbell",
    deviceType: "bell",
    image: "/products/Doorbell Duo.jpg",
    imageStyle: { objectFit: "cover", padding: "0" },
    badge: null,
    price: 159,
    was: 179.99,
    tagline: "Slim wireless doorbell with a plug-in chime.",
    description:
      "Duo is a fuss-free wireless doorbell — slim, weatherproof and easy to mount, with an included chime and PIR sensing so you never miss a visitor.",
    feature: ["Wireless", "Chime", "PIR", "Remote"],
    unlock: ["Phone"],
    highlights: [
      { icon: "Bell", title: "Plug-in chime", body: "A wireless chime you can place anywhere in the home." },
      { icon: "Camera", title: "Clear view", body: "Wide-angle camera with night vision for round-the-clock cover." },
      { icon: "Phone", title: "Remote access", body: "Answer and watch from the Arpha app wherever you are." },
    ],
    specs: [
      { k: "Resolution", v: "1080P" },
      { k: "Field of view", v: "162°" },
      { k: "Detection", v: "PIR motion" },
      { k: "Chime", v: "Included" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz" },
      { k: "Power", v: "Rechargeable battery" },
      { k: "Weather rating", v: "IP54" },
    ],
  },
  {
    slug: "battery-k25",
    name: "K25 Battery",
    model: "",
    category: "IP Camera",
    sub: "Smart Camera",
    deviceType: "cam",
    badge: null,
    price: 119,
    was: 149,
    tagline: "Pan-tilt battery camera with motion tracking.",
    description:
      "The K25 watches the room and follows the action. A pan-tilt head with motion tracking, colour night vision and live two-way audio — all running on battery, so it goes wherever you need cover.",
    feature: ["Pan/Tilt", "Battery", "Tracking", "Two-Way"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "Pan & tilt", body: "A motorised head that scans the room and tracks movement." },
      { icon: "Battery", title: "Wire-free", body: "Rechargeable battery means no outlet, no cabling, anywhere." },
      { icon: "Voice", title: "Two-way audio", body: "Hear and speak to the room from the Arpha app." },
    ],
    specs: [
      { k: "Resolution", v: "2K" },
      { k: "Movement", v: "Pan / tilt + tracking" },
      { k: "Night vision", v: "Colour" },
      { k: "Audio", v: "Two-way" },
      { k: "Connectivity", v: "Wi-Fi 2.4GHz" },
      { k: "Power", v: "Rechargeable battery" },
      { k: "Storage", v: "Cloud / microSD" },
    ],
  },
  {
    slug: "poe-k15",
    name: "K15 POE",
    model: "",
    category: "IP Camera",
    sub: "Smart Camera",
    deviceType: "cam",
    badge: null,
    price: 129,
    was: 149,
    tagline: "Always-on PoE camera for continuous recording.",
    description:
      "The K15 runs on Power-over-Ethernet for a single-cable install and uninterrupted recording — ideal for entrances, driveways and anywhere you want eyes around the clock.",
    feature: ["PoE", "24/7", "Pan/Tilt", "Tracking"],
    unlock: [],
    highlights: [
      { icon: "Plug", title: "Single-cable PoE", body: "Power and data over one Ethernet cable for reliable, always-on cover." },
      { icon: "Camera", title: "Pan & tilt", body: "Motorised tracking keeps moving subjects in frame." },
      { icon: "ShieldCheck", title: "Continuous record", body: "24/7 recording with no battery to swap or recharge." },
    ],
    specs: [
      { k: "Resolution", v: "2K" },
      { k: "Movement", v: "Pan / tilt + tracking" },
      { k: "Night vision", v: "Colour" },
      { k: "Audio", v: "Two-way" },
      { k: "Connectivity", v: "PoE Ethernet" },
      { k: "Recording", v: "24/7" },
      { k: "Storage", v: "NVR / cloud" },
    ],
  },
  {
    slug: "m660",
    name: "M660",
    model: "M660",
    category: "Dash Cam",
    sub: "Smart Driving",
    deviceType: "dash",
    image: "/products/M660.png",
    badge: "3-channel",
    price: 249,
    was: 299,
    tagline: "Three-channel driving recorder with night clarity.",
    description:
      "The M660 records the road ahead, the cabin and the rear at once. Wide field of view, strong night vision and the same Arpha reliability you trust at the front door — now for the drive.",
    feature: ["3 Camera", "Night Vision", "Wide FOV", "Loop"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "Three channels", body: "Front, cabin and rear captured together in one device." },
      { icon: "Weather", title: "Night vision", body: "Clear footage after dark and in low light." },
      { icon: "Bolt", title: "Smart capture", body: "Loop recording with impact-triggered event saving." },
    ],
    specs: [
      { k: "Channels", v: "3 (front / cabin / rear)" },
      { k: "Resolution", v: "Up to 2K" },
      { k: "Field of view", v: "Wide-angle" },
      { k: "Night vision", v: "Yes" },
      { k: "Recording", v: "Loop + event" },
      { k: "Storage", v: "microSD" },
    ],
  },
  {
    slug: "m350",
    name: "M350",
    model: "M350",
    category: "Dash Cam",
    sub: "Smart Driving",
    deviceType: "dash",
    image: "/products/m350 v2.png",
    badge: null,
    price: 119,
    was: 199,
    tagline: "Dual-channel dash cam with front and cabin view.",
    description:
      "A compact dual-channel recorder that keeps an eye on the road and the cabin — straightforward, dependable footage for everyday driving and ride-share peace of mind.",
    feature: ["2 Camera", "Night Vision", "Loop", "Compact"],
    unlock: [],
    highlights: [
      { icon: "Camera", title: "Front & cabin", body: "Two channels covering the road ahead and inside the car." },
      { icon: "Weather", title: "Low-light ready", body: "Night vision keeps plates and faces legible after dark." },
      { icon: "Bolt", title: "Loop & event", body: "Continuous loop recording with automatic incident saving." },
    ],
    specs: [
      { k: "Channels", v: "2 (front / cabin)" },
      { k: "Resolution", v: "1080P" },
      { k: "Night vision", v: "Yes" },
      { k: "Recording", v: "Loop + event" },
      { k: "Storage", v: "microSD" },
      { k: "Mount", v: "Adhesive" },
    ],
  },
];

export function getProduct(slug) {
  return PRODUCTS.find((p) => p.slug === slug);
}
export function getByCategory(key) {
  return PRODUCTS.filter((p) => p.category === key);
}
export function getRelated(slug, n = 3) {
  const cur = getProduct(slug);
  if (!cur) return [];
  const same = PRODUCTS.filter((p) => p.category === cur.category && p.slug !== slug);
  const rest = PRODUCTS.filter((p) => p.category !== cur.category);
  return [...same, ...rest].slice(0, n);
}
